"""add workout fields to Entry

Revision ID: 34861e8d0e0c
Revises: 
Create Date: 2025-11-30 20:19:30.941956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34861e8d0e0c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workout_type', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('intensity', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_column('intensity')
        batch_op.drop_column('duration')
        batch_op.drop_column('workout_type')

    # ### end Alembic commands ###
